- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles_cq: ''
    ~/.bashrc:
    ~/.bash:
    ~/.bash_profile:

- shell:
    - [git submodule update --init --recursive, Installing submodules]
